# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: "node_js"
node_js:
  - "node"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.yarn-cache"
    - "bower_components"
    - "node_modules"
    - "typings"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
